apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac-logs-collector.yaml
  - logs-collector.yaml
  - metrics-collector.yaml

helmCharts:
  - name: opentelemetry-operator
    repo: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts
    includeCRDs: true
    namespace: monitoring
    version: 0.100.0
    releaseName: opentelemetry-operator
    valuesFile: values.yaml
