apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: metrics
  namespace: monitoring
spec:
  mode: deployment
  serviceAccount: metrics-collector
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      k8s_cluster:
        collection_interval: 60s

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
      deltatocumulative:
        max_stale: 5m
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128

    exporters:
      debug:
        verbosity: detailed
      otlphttp/victoriametrics:
        # https://docs.victoriametrics.com/guides/getting-started-with-opentelemetry/#victoriametrics
        metrics_endpoint: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local:8428/opentelemetry/v1/metrics
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [ otlp, k8s_cluster ]
          processors: [ deltatocumulative, batch, memory_limiter ]
          exporters: [ otlphttp/victoriametrics ]
