apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - metrics-server
  - cert-manager
  - grafana
  - otel
#  - prometheus-operator-crds
  - victoria-metrics
  - apps/whoami
