apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - victoria-logs.yaml
  - victoria-metrics.yaml

helmCharts:
  - name: victoria-metrics-operator
    repo: oci://ghcr.io/victoriametrics/helm-charts/
    includeCRDs: true
    namespace: monitoring
    version: 0.57.1
    releaseName: victoria-metrics-operator
    valuesFile: values.yaml
