apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: main
  plugins:
    - name: victoriametrics-metrics-datasource
      version: 0.19.7
  datasource:
    name: "Victoria Metrics"
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local:8428
