apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    grafana: main
spec:
  disableDefaultAdminSecret: true
  version: 12.3.0
  config:
    security:
      admin_user: admin
      admin_password: admin
