apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    grafana: main
spec:
  version: 12.3.0
  config:
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "true"
      org_role: Admin
