apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  - grafana-admin-credentials.yaml
  - datasource-vm-logs.yaml
  - datasource-vm-metrics.yaml

helmCharts:
  - name: grafana-operator
    repo: oci://ghcr.io/grafana/helm-charts
    includeCRDs: true
    namespace: monitoring
    version: v5.20.0
    releaseName: grafana-operator
    valuesFile: values.yaml
